### ISSUE TITLE
iOS install issue

### ISSUE THREAD

**Issue by Yorik0512** [sicpa-dlab/didcomm-react-native#44]
Hey guys,

Look that you started support iOS, it's great news!
But when I was trying to install pods for iOS I caught an error: 
`[!] Unable to find a specification for 'DidcommSDK' depended upon by 'didcomm-react-native'`

Could you help me with that error?

Thanks in advice.

**Comment by Yorik0512** [comment]
Previous issue resolved. But found another one:
- iOS build compile successfully 
- When I run app I catch error in log:
```
 LOG  Resolvers registered: 0588f018-d27a-46b0-b93a-c4bc509bbcce
 LOG  Resolvers unregistered: 0588f018-d27a-46b0-b93a-c4bc509bbcce
 ERROR  [Error: The operation couldn’t be completed. (DidcommSDK.ErrorKind error 0.)]
```

**Comment by rodrigofranzoi** [comment]
Hello @Yorik0512,

Could you describe the steps to reproduce the error? Are you running the demo right?
Also, are you running on a physical device or simulator?

Thanks!

**Comment by Yorik0512** [comment]
Hi @rodrigofranzoi 

I just cloned repo and run demo by the manual:
yarn bootstrap
cd ./demo/ios && arch -x86_64 pod install && cd ./../..
arch -x86_64 yarn demo ios
I'm running on simulator (iPhone 13), M1 Mac.

**Comment by rodrigofranzoi** [comment]
Hi @Yorik0512 

I fixed this issue here: https://github.com/sicpa-dlab/didcomm-react-native/pull/46

Thanks!

**Comment by AlexAndrei98** [comment]
> Hey guys,
> 
> Look that you started support iOS, it's great news! But when I was trying to install pods for iOS I caught an error: `[!] Unable to find a specification for 'DidcommSDK' depended upon by 'didcomm-react-native'`
> 
> Could you help me with that error?
> 
> Thanks in advice.

Hey Yuri, how did you get around that error? when I try to install this package in a different repo and build the ios app I am still stuck here
