### ISSUE TITLE
iOS Podfile.loc issue

### ISSUE THREAD

**Issue by Yorik0512** [sicpa-dlab/didcomm-react-native#53]
Hi there,

When I deleted `Podfile.loc` file in my project and tried to recreate it throw run terminal command `pod install` I caught an issue:
```
[!] Unable to find a specification for `FlipperKit (= 0.125.0)`

You have either:
 * mistyped the name or version.
 * not added the source repo that hosts the Podspec to your Podfile.
```

When I did the same in demo project I also caught the issue:
```
[!] Unable to find a specification for `hermes-engine (~> 0.11.0)`

You have either:
 * out-of-date source repos which you can update with `pod repo update` or with `pod install --repo-update`.
 * mistyped the name or version.
 * not added the source repo that hosts the Podspec to your Podfile.

```

@rodrigofranzoi Could you help me with that issue?

Thanks in advance.

**Comment by rodrigofranzoi** [comment]
Hey @Yorik0512,

Please add the source of Cocoapods into your `Podfile` in to fetch other dependencies besides didcomm-rust:
```
source 'https://github.com/CocoaPods/Specs.git'
```

Here is the PR with the changes on demo:
https://github.com/sicpa-dlab/didcomm-react-native/pull/54
